# to use the env-var "GIT_CLONE_PATH", set the following in
# ./gitlab-runner/config.toml under [[runners]]:
#   [runners.custom_build_dir]
#     enabled = true
# This will prevent git clone conflicts for jobs ran in parallel

variables:
  GIT_DEPTH: 10
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME/$CI_JOB_NAME

stages:
  - info
  - build
  - valgrind
  - check-cases
  - code-analysis
  - deploy

show-env-vars:
  stage: info
  variables:
    GIT_STRATEGY: none
    SEP: "##################################################################"
    S00: "commit date - "
    S01: "project: ${CI_PROJECT_PATH}"
    S02: "branch: ${CI_COMMIT_REF_NAME}"
    S03: "commit: ${CI_COMMIT_SHA}"
    S04: "commit msg: ${CI_COMMIT_MESSAGE}"
    S05: "clone base path: "
    S06: "runner token: ${CI_RUNNER_SHORT_TOKEN}"
  script:
    - echo -e "${SEP}\n${S00}$(date)\n${SEP}\n${S01}\n${S02}\n${S03}\n${S04}\n${SEP}\n${S05}${GIT_CLONE_PATH}\n${S06}\n${SEP}"

documentation:
  stage: build
  script:
    - source hpc-module-loads/eve.chs-conda01
    - module load GCCcore/9.3.0 texlive/2020
    # use doxygen from the chs conda environment
    - doxygen doc/doxygen.config > doxygen_log_dev.txt
    # create pdf documentation
    - cd latex/ && make > ../doxygen_latex_dev.txt
    - cp refman.pdf ../html/mhm_doc.pdf
    - cp refman.pdf ../mhm_doc_dev.pdf
    - cd .. && mv html html_dev
    - mv doxygen_warn.txt doxygen_warn_dev.txt
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - html_dev
      - mhm_doc_dev.pdf
      - doxygen_log_dev.txt
      - doxygen_latex_dev.txt
      - doxygen_warn_dev.txt
  when: always

documentation_stable:
  only:
    - develop
  stage: build
  variables:
    GIT_DEPTH: 0  # to have all tags
    GIT_FETCH_EXTRA_FLAGS: --all --prune --quiet
  script:
    - source hpc-module-loads/eve.chs-conda01
    # doc for latest version tag
    - git checkout $(git describe --match "v*" --abbrev=0 --tags $(git rev-list --tags --max-count=1))
    - module load GCCcore/9.3.0 texlive/2020
    # use doxygen from the chs conda environment
    - doxygen doc/doxygen.config > doxygen_log_tag.txt
    - cd latex/ && make > ../doxygen_latex_tag.txt
    - cp refman.pdf ../html/mhm_doc.pdf
    - cp refman.pdf ../mhm_doc_tag.pdf
    - cd .. && mv html html_tag
    - mv doxygen_warn.txt doxygen_warn_tag.txt
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - html_tag
      - mhm_doc_tag.pdf
      - doxygen_log_tag.txt
      - doxygen_latex_tag.txt
      - doxygen_warn_tag.txt
  when: always

cmake-nagfor62:
  stage: build
  script:
    - source hpc-module-loads/eve.nagfor62
    - source CI-scripts/compile
    - source CI-scripts/compile_debug
  artifacts:
    paths:
    - mhm
    - mhm_debug

cmake-gfortran73:
  stage: build
  script:
    - source hpc-module-loads/eve.gfortran73
    - source CI-scripts/compile
    - source CI-scripts/compile_debug
    - source CI-scripts/compile_OpenMP
    - source CI-scripts/compile_OpenMP_debug
  artifacts:
    paths:
    - mhm
    - mhm_debug
    - mhm_openmp
    - mhm_openmp_debug

cmake-gfortran73MPI:
  stage: build
  script:
    - source hpc-module-loads/eve.gfortran73MPI
    - source CI-scripts/compile_MPI
    - source CI-scripts/compile_MPI_debug
  artifacts:
    paths:
    - mhm_mpi
    - mhm_mpi_debug

cmake-gfortran83:
  stage: build
  script:
    - source hpc-module-loads/eve.gfortran83
    - source CI-scripts/compile
    - source CI-scripts/compile_debug
    - source CI-scripts/compile_OpenMP
    - source CI-scripts/compile_OpenMP_debug
  artifacts:
    paths:
    - mhm
    - mhm_debug
    - mhm_openmp
    - mhm_openmp_debug

cmake-gfortran83MPI:
  stage: build
  script:
    - source hpc-module-loads/eve.gfortran83MPI
    - source CI-scripts/compile_MPI
    - source CI-scripts/compile_MPI_debug
  artifacts:
    paths:
    - mhm_mpi
    - mhm_mpi_debug

cmake-intel18:
  stage: build
  script:
    - source hpc-module-loads/eve.intel18
    - source CI-scripts/compile
    - source CI-scripts/compile_debug
    - source CI-scripts/compile_OpenMP
    - source CI-scripts/compile_OpenMP_debug
  artifacts:
    paths:
    - mhm
    - mhm_debug
    - mhm_openmp
    - mhm_openmp_debug

cmake-intel18MPI:
  stage: build
  script:
    - source hpc-module-loads/eve.intel18MPI
    - source CI-scripts/compile_MPI
    - source CI-scripts/compile_MPI_debug
  artifacts:
    paths:
    - mhm_mpi
    - mhm_mpi_debug

cmake-intel19:
  stage: build
  script:
    - source hpc-module-loads/eve.intel19
    - source CI-scripts/compile
    - source CI-scripts/compile_debug
    - source CI-scripts/compile_OpenMP
    - source CI-scripts/compile_OpenMP_debug
  artifacts:
    paths:
    - mhm
    - mhm_debug
    - mhm_openmp
    - mhm_openmp_debug

cmake-intel19MPI:
  stage: build
  script:
    - source hpc-module-loads/eve.intel19MPI
    - source CI-scripts/compile_MPI
    - source CI-scripts/compile_MPI_debug
  artifacts:
    paths:
    - mhm_mpi
    - mhm_mpi_debug

valgrind-nagfor62:
  when: always
  stage: valgrind
  needs:
    - job: cmake-nagfor62
      artifacts: true
  script:
    - source hpc-module-loads/eve.nagfor62
    - module load Anaconda3
    - source activate /global/apps/mhm_checks/mhm_env
    - valgrind --version
    - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose ./mhm_debug
    # execute mem-use check
    - valgrind --tool=massif --stacks=yes --time-unit=i --massif-out-file=massif.out.0 ./mhm_debug
    - ms_print massif.out.0
  artifacts:
    paths:
    - massif.out.0

valgrind-gfortran83:
  when: always
  stage: valgrind
  needs:
    - job: cmake-gfortran83
      artifacts: true
  script:
    - source hpc-module-loads/eve.gfortran83
    - module load Anaconda3
    - source activate /global/apps/mhm_checks/mhm_env
    - valgrind --version
    - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose ./mhm_debug
    # execute mem-use check
    - valgrind --tool=massif --stacks=yes --time-unit=i --massif-out-file=massif.out.0 ./mhm_debug
    - ms_print massif.out.0
  artifacts:
    paths:
    - massif.out.0

valgrind-intel19:
  when: always
  stage: valgrind
  needs:
    - job: cmake-intel19
      artifacts: true
  script:
    - source hpc-module-loads/eve.intel19
    - module load Anaconda3
    - source activate /global/apps/mhm_checks/mhm_env
    - valgrind --version
    - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose ./mhm_debug
    # execute mem-use check
    - valgrind --tool=massif --stacks=yes --time-unit=i --massif-out-file=massif.out.0 ./mhm_debug
    - ms_print massif.out.0
  artifacts:
    paths:
    - massif.out.0

check-nagfor62:
  when: always
  stage: check-cases
  needs:
    - job: cmake-nagfor62
      artifacts: true
  script:
    - source hpc-module-loads/eve.nagfor62
    - source CI-scripts/pre_check
    - python -u run_mhm_checks.py -l logs -e ../mhm
  artifacts:
    when: always
    paths:
    - check/logs/

check-nagfor62DEBUG:
  when: always
  stage: check-cases
  needs:
    - job: cmake-nagfor62
      artifacts: true
  script:
    - source hpc-module-loads/eve.nagfor62
    - source CI-scripts/pre_check
    # skip cases with optimization due to overflow in the random-number-generator (NAG uses -ieee=stop in DEBUG)
    - python -u run_mhm_checks.py -l logs -e ../mhm_debug -s case_03 case_06 case_07 case_08 case_11
  artifacts:
    when: always
    paths:
    - check/logs/

check-gfortran73:
  when: always
  stage: check-cases
  needs:
    - job: cmake-gfortran73
      artifacts: true
  script:
    - source hpc-module-loads/eve.gfortran73
    - source CI-scripts/pre_check
    - python -u run_mhm_checks.py -l logs -e ../mhm_debug ../mhm ../mhm_openmp_debug ../mhm_openmp -t 4
  artifacts:
    when: always
    paths:
    - check/logs/

check-gfortran73MPI:
  when: always
  stage: check-cases
  needs:
    - job: cmake-gfortran73MPI
      artifacts: true
  script:
    - source hpc-module-loads/eve.gfortran73MPI
    - source CI-scripts/pre_check
    - python -u run_mhm_checks.py -l logs -e ../mhm_mpi_debug ../mhm_mpi -m 4
  artifacts:
    when: always
    paths:
    - check/logs/

check-gfortran83:
  when: always
  stage: check-cases
  needs:
    - job: cmake-gfortran83
      artifacts: true
  script:
    - source hpc-module-loads/eve.gfortran83
    - source CI-scripts/pre_check
    - python -u run_mhm_checks.py -l logs -e ../mhm_debug ../mhm ../mhm_openmp_debug ../mhm_openmp -t 4
  artifacts:
    when: always
    paths:
    - check/logs/

check-gfortran83MPI:
  when: always
  stage: check-cases
  needs:
    - job: cmake-gfortran83MPI
      artifacts: true
  script:
    - source hpc-module-loads/eve.gfortran83MPI
    - source CI-scripts/pre_check
    - python -u run_mhm_checks.py -l logs -e ../mhm_mpi_debug ../mhm_mpi -m 4
  artifacts:
    when: always
    paths:
    - check/logs/

check-intel18:
  when: always
  stage: check-cases
  needs:
    - job: cmake-intel18
      artifacts: true
  script:
    - source hpc-module-loads/eve.intel18
    - source CI-scripts/pre_check
    - python -u run_mhm_checks.py -l logs -e ../mhm_debug ../mhm ../mhm_openmp_debug ../mhm_openmp -t 4
  artifacts:
    when: always
    paths:
    - check/logs/

check-intel18MPI:
  when: always
  stage: check-cases
  needs:
    - job: cmake-intel18MPI
      artifacts: true
  script:
    - source hpc-module-loads/eve.intel18MPI
    - source CI-scripts/pre_check
    - python -u run_mhm_checks.py -l logs -e ../mhm_mpi_debug ../mhm_mpi -m 4
  artifacts:
    when: always
    paths:
    - check/logs/

check-intel19:
  when: always
  stage: check-cases
  needs:
    - job: cmake-intel19
      artifacts: true
  script:
    - source hpc-module-loads/eve.intel19
    - source CI-scripts/pre_check
    - python -u run_mhm_checks.py -l logs -e ../mhm_debug ../mhm ../mhm_openmp_debug ../mhm_openmp -t 4
  artifacts:
    when: always
    paths:
    - check/logs/

check-intel19MPI:
  when: always
  stage: check-cases
  needs:
    - job: cmake-intel19MPI
      artifacts: true
  script:
    - source hpc-module-loads/eve.intel19MPI
    - source CI-scripts/pre_check
    - python -u run_mhm_checks.py -l logs -e ../mhm_mpi_debug ../mhm_mpi -m 4
  artifacts:
    when: always
    paths:
    - check/logs/

unittest-gfortran83:
  when: always
  stage: code-analysis
  needs:
    - job: cmake-gfortran83
  script:
    # we need pfUnit
    - source hpc-module-loads/eve.gfortran83
    # create build folder
    - mkdir build && cd build
    # run cmake with testing support and build mhm
    - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON ..
    - make -j 4
    # run all pfUnit tests in src/tests
    - ctest -V

coverage:
  when: always
  stage: code-analysis
  needs: []
  script:
    # gcov is part of GCC
    - source hpc-module-loads/eve.chs-conda01
    # run cmake with coverage support
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_WITH_COVERAGE=ON -B build
    - cmake --build build --parallel
    # run all check-case for coverage calculation
    - cd build && make mhm_coverage_CI
    # copy the output to a top-level folder
    - cd .. && mkdir coverage
    - cp build/mhm_coverage_CI/* coverage -R
  artifacts:
    when: always
    paths:
    - coverage

pages:
  only:
    - develop
  stage: deploy
  dependencies:
    - documentation
    - documentation_stable
    - coverage
  script:
    # create public dir (remove if already present)
    - test -d public && rm -rf public
    - mkdir -p public
    # create the subdir
    - mkdir public/stable/
    - mkdir public/latest/
    # copy the doxygen generated html page to the public site
    - cp html_tag/* public/stable/ -R
    - cp html_dev/* public/latest/ -R
    # create an index.html that redirects to the master documentation (in master folder)
    - cp doc/html_files/index.html public/
    # create the coverage site
    - mkdir -p public/coverage
    - cp coverage/* public/coverage/ -R
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - public
  when: always
