name: Continuous Integration

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_macOS:
    name: Build on macOS
    runs-on: macos-11
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mhm
          python-version: 3.6
          channels: conda-forge
          allow-softlinks: true
          channel-priority: strict
          show-channel-urls: true
          use-only-tar-bz2: true
      - name: install
        run: |
          conda install -y fypp cmake make fortran-compiler netcdf-fortran=4.5.3
      - name: conda list
        run: |
          conda list
      - name: conda info
        run: |
          conda info
      - name: compile mhm
        run: |
          cd mhm
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCPM_forces_SOURCE=../forces
          cmake --build build --parallel
